version: '3'

services:
  nginx:
    build: 
      context: ./requirements/nginx/
    # image: nginx:latest
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    restart: on-failure
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception

  mariadb:
    build:
      context: ./requirements/mariadb/
    container_name: ${COMPOSE_PROJECT_NAME}_mariadb
    restart: on-failure
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    #image: wordpress:php7.4-fpm
    build:
      context: ./requirements/wordpress/
    container_name: ${COMPOSE_PROJECT_NAME}_wordpress
    restart: on-failure
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception

volumes:
  mariadb_data:
    driver: local
    name: mariadb_data
    driver_opts:
      type: none
      o: bind
      device: /home/josgarci/data/mariadb_vol
  wordpress_data:
    driver: local
    name: wordpress_data
    driver_opts:
      type: none
      o: bind
      device: /home/josgarci/data/wordpress_vol

networks:
  inception:
    driver: bridge
