version: '3'

services:
  nginx:
    build: 
      context: ./requirements/nginx/
    image: nginx:${COMPOSE_PROJECT_NAME}
    container_name: nginx
    restart: on-failure
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception

  mariadb:
    build:
      context: ./requirements/mariadb/
    image: mariadb:${COMPOSE_PROJECT_NAME}
    container_name: mariadb
    restart: on-failure
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress/
    image: wordpress:${COMPOSE_PROJECT_NAME}
    container_name: wordpress
    restart: on-failure
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception

volumes:
  mariadb_data:
    driver: local
    name: mariadb_data
    driver_opts:
      type: none
      o: bind
      device: /home/josgarci/data/mariadb_vol
  wordpress_data:
    driver: local
    name: wordpress_data
    driver_opts:
      type: none
      o: bind
      device: /home/josgarci/data/wordpress_vol

networks:
  inception:
    driver: bridge
